#!/usr/bin/env fish

# Unified command hub for this repository's sandbox/key scripts.
# Why: one memorisable entrypoint reduces operator error and shortens onboarding.

set -l script_dir (cd (dirname (status filename)); pwd)

function __sandboxctl_help
    echo "sandboxctl — unified hub for sandbox, VM, and key-lifecycle scripts"
    echo ""
    echo "Description:"
    echo "  One entrypoint that dispatches to every sandbox/VM/key tool in this"
    echo "  repo. Use 'list' to see the mapping, 'tutorial <topic>' for ready-to-"
    echo "  copy quickstarts, or any subcommand below to forward args to the"
    echo "  underlying script. For an interactive launcher, see 'slop'."
    echo ""
    echo "Usage:"
    echo "  scripts/sandboxctl.fish help"
    echo "  scripts/sandboxctl.fish list"
    echo "  scripts/sandboxctl.fish tutorial <topic>"
    echo "  scripts/sandboxctl.fish docker         <args...>   -> agent-sandbox"
    echo "  scripts/sandboxctl.fish docker-tools   <args...>   -> agent-sandbox-tools"
    echo "  scripts/sandboxctl.fish local          <args...>   -> macos-sandbox"
    echo "  scripts/sandboxctl.fish brew-vm        <args...>   -> brew-vm"
    echo "  scripts/sandboxctl.fish github         <args...>   -> llm-gh-key"
    echo "  scripts/sandboxctl.fish forgejo        <args...>   -> llm-forgejo-key"
    echo "  scripts/sandboxctl.fish radicle        <args...>   -> llm-radicle-access"
    echo "  scripts/sandboxctl.fish safe-npm                   -> safe-npm-install"
    echo "  scripts/sandboxctl.fish safe-uv        <args...>   -> safe-uv"
    echo "  scripts/sandboxctl.fish pinning                    -> check-pinning"
    echo ""
    echo "Topics: docker, local, brew-vm, github-keys, forgejo-keys, radicle-access, network-limiting, file-sharing"
    echo ""
    echo "Examples:"
    echo "  # Discover what each subcommand maps to"
    echo "  scripts/sandboxctl.fish list"
    echo ""
    echo "  # See a focused quickstart for one topic"
    echo "  scripts/sandboxctl.fish tutorial docker"
    echo "  scripts/sandboxctl.fish tutorial github-keys"
    echo ""
    echo "  # Forward args to the underlying tool"
    echo "  scripts/sandboxctl.fish local run --repo-root-access -- /bin/pwd"
    echo "  scripts/sandboxctl.fish github here create-pair       # uses llm-gh-key here"
    echo ""
    echo "Notes:"
    echo "  - For an interactive menu across all of these tools, run: slop"
    echo "  - Per-tool TUIs exist: llm-gh-key tui, llm-forgejo-key tui, llm-radicle-access tui."
    echo "  - Each subcommand prints its own --help when given no args or --help."
    echo "  - Full reference: README.md."
end

function __sandboxctl_help_to_stderr
    __sandboxctl_help 1>&2
end

function __sandboxctl_list
    echo "Commands:"
    echo "  docker         -> scripts/agent-sandbox.fish (agent-sandbox ...)"
    echo "  docker-tools   -> scripts/agent-sandbox-tools.fish (agent-sandbox-tools ...)"
    echo "  local          -> scripts/macos-sandbox.fish (macos-sandbox ...)"
    echo "  brew-vm        -> scripts/brew-vm.fish (brew-vm ...)"
    echo "  github         -> scripts/llm-github-keys.fish (llm-gh-key ...)"
    echo "  forgejo        -> scripts/llm-forgejo-keys.fish (llm-forgejo-key ...)"
    echo "  radicle        -> scripts/llm-radicle-access.fish (llm-radicle-access ...)"
    echo "  safe-npm       -> scripts/safe-npm-install.fish (safe-npm-install)"
    echo "  safe-uv        -> scripts/safe-uv-install.fish (safe-uv ...)"
    echo "  pinning        -> scripts/check-pinning.fish"
end

# Each tutorial topic body is autogenerated from the matching README how-to
# section so the quickstart text and the docs cannot drift. Sections without
# a direct README counterpart (currently: file-sharing) keep hand-written
# bodies and no AUTOGEN block.

function __sandboxctl_tutorial_docker
    echo "Docker sandbox quickstart (from README → 'How to run any agent behind Docker + URL allowlist proxy'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to run any agent behind Docker + URL allowlist proxy"
    echo 'Start the proxy:'
    echo '  docker compose -f examples/docker-compose.yml build agent'
    echo '  docker compose -f examples/docker-compose.yml up -d proxy'
    echo
    echo 'Run agent container through proxy:'
    echo '  docker compose -f examples/docker-compose.yml run --rm agent'
    echo
    echo 'Verify blocking:'
    echo '  docker compose -f examples/docker-compose.yml run --rm agent sh -lc \'curl -I https://example.com\''
    # END AUTOGEN: examples
end

function __sandboxctl_tutorial_local
    echo "Local macOS sandbox quickstart (from README → 'How to use optional local sandbox-exec layer on macOS'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to use optional local sandbox-exec layer on macOS"
    echo 'Load helper:'
    echo '  source scripts/macos-sandbox.fish'
    echo
    echo 'Run command with default cwd scope and strict egress deny:'
    echo '  macos-sandbox run -- /bin/pwd'
    echo
    echo 'Run command with repository-root scope (alternative to default cwd scope):'
    echo '  macos-sandbox run --repo-root-access -- /usr/bin/env ls'
    echo '  macos-sandbox run --path-scope repo-root -- /usr/bin/env ls'
    echo
    echo 'Use through the unified hub:'
    echo '  scripts/sandboxctl.fish local run --repo-root-access -- /bin/pwd'
    echo
    echo 'Add explicit additional paths only when needed:'
    echo '  macos-sandbox run --allow-read ~/.config --allow-write ./tmp -- /usr/bin/env ls'
    # END AUTOGEN: examples
    echo ""
    echo "Prefer Docker/VM for stronger isolation when executing untrusted workflows."
end

function __sandboxctl_tutorial_brew_vm
    echo "Brew VM quickstart (from README → 'How to sandbox brew with disposable Tart VMs'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to sandbox brew with disposable Tart VMs"
    echo 'Load VM helper:'
    echo '  source scripts/brew-vm.fish'
    echo
    echo 'Create base template once:'
    echo '  brew-vm create-base'
    echo
    echo 'Install formula in disposable VM session:'
    echo '  set -x BREW_VM_PROXY_URL http://<proxy-host>:3128'
    echo '  brew-vm install --network-policy strict-egress <formula>'
    echo
    echo 'Optional: inspect manually in VM shell:'
    echo '  set -x BREW_VM_KEEP_SESSION true'
    echo '  brew-vm install <formula>'
    echo '  brew-vm shell'
    echo '  brew-vm destroy'
    echo
    echo 'Share files explicitly with host:'
    echo '  brew-vm copy-in ./local-file.txt /tmp/llm-share/local-file.txt'
    echo '  brew-vm copy-out /tmp/llm-share/result.txt ./result.txt'
    echo
    echo 'Verify policy enforcement:'
    echo '  brew-vm verify-network'
    # END AUTOGEN: examples
end

function __sandboxctl_tutorial_github_keys
    echo "GitHub deploy-key quickstart (from README → 'How to manage ephemeral GitHub SSH deploy keys'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to manage ephemeral GitHub SSH deploy keys"
    echo 'Load helper:'
    echo '  source scripts/llm-github-keys.fish'
    echo
    echo 'Create RO + RW key pair for one repo (default TTL 24h):'
    echo '  llm-gh-key create-pair --repo <owner>/<repo> --name session-1 --ttl 24h'
    echo '  llm-gh-key create-pair --repo <owner>/<repo> --name session-1 --ttl 24h --install-ssh-config --host-prefix github-llm'
    echo
    echo 'List deploy keys on repo:'
    echo '  llm-gh-key list --repo <owner>/<repo>'
    echo
    echo 'Revoke one key by id:'
    echo '  llm-gh-key revoke --repo <owner>/<repo> --id <key-id>'
    echo
    echo 'Revoke keys by title pattern or expiration:'
    echo '  llm-gh-key revoke-by-title --repo <owner>/<repo> --match \'^llm-agent:\''
    echo '  llm-gh-key revoke-expired --repo <owner>/<repo>'
    echo
    echo 'Generate or install SSH config aliases manually:'
    echo '  llm-gh-key print-ssh-config --ro-key ~/.ssh/llm_agent_github_ro_<stamp> --rw-key ~/.ssh/llm_agent_github_rw_<stamp>'
    echo '  llm-gh-key install-ssh-config --repo <owner>/<repo> --name session-1 --ro-key ~/.ssh/llm_agent_github_ro_<stamp> --rw-key ~/.ssh/llm_agent_github_rw_<stamp>'
    echo
    echo 'Remove old alias blocks from ~/.ssh/config:'
    echo '  llm-gh-key uninstall-ssh-config --repo <owner>/<repo> --name session-1 --yes'
    echo '  llm-gh-key uninstall-ssh-config --marker \'^llm-gh-key:<owner>-<repo>:\' --yes'
    # END AUTOGEN: examples
    echo ""
    echo "Repo-aware shortcuts: llm-gh-key here create-pair | here list | here revoke <id> | here cleanup | here revoke-all"
end

function __sandboxctl_tutorial_forgejo_keys
    echo "Forgejo deploy-key quickstart (from README → 'How to manage ephemeral Forgejo deploy keys (multi-instance)'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to manage ephemeral Forgejo deploy keys (multi-instance)"
    echo 'Load helper:'
    echo '  source scripts/llm-forgejo-keys.fish'
    echo '  llm-forgejo-key bootstrap-config'
    echo
    echo 'Save Forgejo instance profile once:'
    echo '  llm-forgejo-key instance-set --name main --url https://forgejo.example.com --token-env FORGEJO_TOKEN_MAIN'
    echo '  set -x FORGEJO_TOKEN_MAIN <token-with-repo-admin>'
    echo
    echo 'Create RO + RW deploy key pair for one repository:'
    echo '  llm-forgejo-key create-pair --instance main --repo <owner>/<repo> --name session-1 --ttl 24h --install-ssh-config'
    echo
    echo 'List and revoke:'
    echo '  llm-forgejo-key list --instance main --repo <owner>/<repo>'
    echo '  llm-forgejo-key revoke --instance main --repo <owner>/<repo> --id <key-id>'
    echo '  llm-forgejo-key revoke-expired --instance main --repo <owner>/<repo> --yes'
    echo
    echo 'Remove old SSH alias blocks:'
    echo '  llm-forgejo-key uninstall-ssh-config --repo <owner>/<repo> --name session-1 --yes'
    # END AUTOGEN: examples
    echo ""
    echo "Repo-aware shortcuts: llm-forgejo-key here create-pair | here list | here revoke <id> | here cleanup | here revoke-all"
end

function __sandboxctl_tutorial_radicle_access
    echo "Radicle access quickstart (from README → 'How to manage ephemeral Radicle identities across many repos'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to manage ephemeral Radicle identities across many repos"
    echo 'Load helper:'
    echo '  source scripts/llm-radicle-access.fish'
    echo '  llm-radicle-access bootstrap-config'
    echo
    echo 'Create short-lived identity:'
    echo '  llm-radicle-access create-identity --name session-1 --ttl 24h'
    echo
    echo 'Bind identity to current/future repositories by RID:'
    echo '  llm-radicle-access bind-repo --rid <rad:...> --identity-id <identity-id> --access ro'
    echo '  llm-radicle-access bind-repo --rid <rad:...> --identity-id <identity-id> --access rw --note "maintainer tasks"'
    echo
    echo 'Inspect and retire:'
    echo '  llm-radicle-access list-identities'
    echo '  llm-radicle-access list-bindings --all'
    echo '  llm-radicle-access retire-expired --yes'
    echo '  llm-radicle-access unbind-repo --rid <rad:...> --yes'
    echo
    echo 'Print shell export for active identity key:'
    echo '  llm-radicle-access print-env --identity-id <identity-id>'
    # END AUTOGEN: examples
    echo ""
    echo "Repo-aware shortcuts: llm-radicle-access here info | here bind --identity-id <id> --access ro|rw | here unbind | here list-bindings"
end

function __sandboxctl_tutorial_network_limiting
    echo "Network limiting quickstart (from README → 'How to strengthen network limiting'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to strengthen network limiting"
    # END AUTOGEN: examples
end

function __sandboxctl_tutorial_file_sharing
    # No direct README section; this is a synthesis of the brew-vm copy-in/out
    # rules and the docker workspace mount convention.
    echo "File sharing quickstart:"
    echo "  Docker: host repo is /workspace in containers"
    echo "  VM: use explicit transfers only — brew-vm copy-in <host> <guest> / brew-vm copy-out <guest> <host>"
    echo "  Recommended guest share dir: /tmp/llm-share (inside the disposable VM only)"
end

function __sandboxctl_tutorial --argument-names topic
    switch "$topic"
        case docker
            __sandboxctl_tutorial_docker
        case local
            __sandboxctl_tutorial_local
        case brew-vm
            __sandboxctl_tutorial_brew_vm
        case github-keys
            __sandboxctl_tutorial_github_keys
        case forgejo-keys
            __sandboxctl_tutorial_forgejo_keys
        case radicle-access
            __sandboxctl_tutorial_radicle_access
        case network-limiting
            __sandboxctl_tutorial_network_limiting
        case file-sharing
            __sandboxctl_tutorial_file_sharing
        case '*'
            echo "Error: Unknown tutorial topic: $topic" 1>&2
            echo "" 1>&2
            __sandboxctl_help_to_stderr
            return 1
    end
end

if test (count $argv) -eq 0
    __sandboxctl_help
    exit 0
end

set -l cmd "$argv[1]"
set -e argv[1]

switch "$cmd"
    case help --help -h
        __sandboxctl_help
    case list
        __sandboxctl_list
    case tutorial
        if test (count $argv) -ne 1
            echo "Error: 'tutorial' requires exactly one topic." 1>&2
            echo "" 1>&2
            __sandboxctl_help_to_stderr
            exit 1
        end
        __sandboxctl_tutorial "$argv[1]"
    case docker
        fish -c "source '$script_dir/agent-sandbox.fish'; agent-sandbox $argv"
    case docker-tools
        fish -c "source '$script_dir/agent-sandbox-tools.fish'; agent-sandbox-tools $argv"
    case local
        fish -c "source '$script_dir/macos-sandbox.fish'; macos-sandbox $argv"
    case brew-vm
        fish -c "source '$script_dir/brew-vm.fish'; brew-vm $argv"
    case github
        fish -c "source '$script_dir/llm-github-keys.fish'; llm-gh-key $argv"
    case forgejo
        fish -c "source '$script_dir/llm-forgejo-keys.fish'; llm-forgejo-key $argv"
    case radicle
        fish -c "source '$script_dir/llm-radicle-access.fish'; llm-radicle-access $argv"
    case safe-npm
        fish -c "source '$script_dir/safe-npm-install.fish'; safe-npm-install $argv"
    case safe-uv
        fish -c "source '$script_dir/safe-uv-install.fish'; safe-uv $argv"
    case pinning
        fish "$script_dir/check-pinning.fish" $argv
    case '*'
        echo "Error: Unknown command: $cmd" 1>&2
        echo "" 1>&2
        __sandboxctl_help_to_stderr
        exit 1
end
